# Generated by Django 4.2.5 on 2023-09-17 02:37

import base.custom_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo_imovel', base.custom_fields.CodigoField(editable=False, max_length=12, primary_key=True, serialize=False)),
                ('limite_hospedes', models.IntegerField(default=1)),
                ('quantidade_banheiros', models.IntegerField(default=0)),
                ('aceita_animal_estimacao', models.BooleanField(default=False)),
                ('valor_limpeza', models.FloatField(default=0)),
                ('data_ativacao', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
