# Generated by Django 4.2.5 on 2023-09-18 05:54

import base.custom_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('codigo_imovel', base.custom_fields.CodigoField(editable=False, prefix='IMO-', unique=True)),
                ('limite_hospedes', models.PositiveIntegerField(default=1)),
                ('quantidade_banheiros', models.PositiveIntegerField(default=0)),
                ('aceita_animal_estimacao', models.BooleanField(default=False)),
                ('valor_limpeza', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_ativacao', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
