# Generated by Django 4.2.5 on 2023-09-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_alter_imovel_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='valor_limpeza',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
