# Generated by Django 4.2.5 on 2023-09-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_alter_imovel_codigo_imovel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='data_ativacao',
            field=models.DateField(),
        ),
    ]
