# Generated by Django 4.2.5 on 2023-09-17 04:50

from django.db import migrations
from django.core.management import call_command


def carregar_fixtures(apps, schema_editor):
    call_command('importar_imoveis')
    call_command('importar_anuncios')
    call_command('importar_reservas')


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_delete_basemodel'),
    ]

    operations = [
        migrations.RunPython(carregar_fixtures),
    ]
