# Generated by Django 4.2.5 on 2023-09-18 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome_plataforma', models.CharField(max_length=50)),
                ('taxa_plataforma', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anuncios', to='imoveis.imovel')),
            ],
            options={
                'unique_together': {('imovel', 'nome_plataforma')},
            },
        ),
    ]
