# Generated by Django 4.2.5 on 2023-09-17 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_alter_imovel_codigo_imovel'),
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='anuncio',
            unique_together={('imovel', 'nome_plataforma')},
        ),
    ]
