# Generated by Django 4.2.5 on 2023-09-17 02:37

import base.custom_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo_reserva', base.custom_fields.CodigoField(editable=False, max_length=12, primary_key=True, serialize=False)),
                ('data_checkin', models.DateTimeField()),
                ('data_checkout', models.DateTimeField()),
                ('preco_total', models.FloatField()),
                ('comentario', models.CharField(blank=True, max_length=500)),
                ('numero_hospedes', models.IntegerField()),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='anuncios.anuncio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
