# Generated by Django 4.2.5 on 2023-09-18 05:54

import base.custom_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('codigo_reserva', base.custom_fields.CodigoField(editable=False, prefix='RES-', unique=True)),
                ('data_checkin', models.DateField()),
                ('data_checkout', models.DateField()),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comentario', models.CharField(max_length=255)),
                ('numero_hospedes', models.PositiveIntegerField(default=1)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='anuncios.anuncio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
