# Generated by Django 4.2.5 on 2023-09-17 03:56

import base.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='codigo_reserva',
            field=base.custom_fields.CodigoField(editable=False, prefix='RES-', max_length=16, primary_key=True, serialize=False),
        ),
    ]
