# Generated by Django 4.2.5 on 2023-09-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_reserva_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='preco_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
