# Generated by Django 4.2.5 on 2023-09-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_reserva_codigo_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_checkin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_checkout',
            field=models.DateField(),
        ),
    ]
